# NVIDIA RTX 5090 Checker - Fix for GitHub cron scheduling
name: NVIDIA RTX 5090 Checker

on:
  #schedule:
  #  - cron: '*/30 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Python
        run: sudo apt update && sudo apt install -y python3

      - name: Install dependencies
        run: pip install requests

      - name: Run the script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python nvidia_check.py
